language: python
python:
  - "2.7"

# System dependencies
before_install:
  - sudo apt-get install -y python-dev python-pip libhdf5-serial-dev pkg-config

# Install dependencies (DeepFramework + dependencies in setup.py)
install:
  - pip install -r requirements.txt
  - pip install .

# Tests execution
script: python -m pytest tests/